export const data = 
  {
    customerCode: 'CUST-001',
    customerName: 'Muhammad Ali',
    cnic: '42101-1234567-9',
    branchName: 'Karachi Main Branch',
    branchContact: '+92-21-34567890',
    invoices: [
      {
        instId: 'INV-1001',
        description: 'Laptop Installment – Jan 2025',
        dueDate: '2025-01-10',
        totalInstallment: 25000,
        installmentDue: 0,
        status: 'Paid',
        paidAmount: 25000,
        remarks: 'Fully cleared',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1002',
        description: 'Laptop Installment – Feb 2025',
        dueDate: '2025-02-10',
        totalInstallment: 25000,
        installmentDue: 10000,
        status: 'Partial',
        paidAmount: 15000,
        remarks: 'Partial payment received',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1003',
        description: 'Laptop Installment – Mar 2025',
        dueDate: '2025-03-10',
        totalInstallment: 25000,
        installmentDue: 25000,
        status: 'Overdue',
        paidAmount: 0,
        remarks: 'Payment pending',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1004',
        description: 'Laptop Installment – Apr 2025',
        dueDate: '2025-04-10',
        totalInstallment: 25000,
        installmentDue: 25000,
        status: 'Overdue',
        paidAmount: 0,
        remarks: 'Overdue since April',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1005',
        description: 'Laptop Installment – May 2025',
        dueDate: '2025-05-10',
        totalInstallment: 25000,
        installmentDue: 25000,
        status: 'Current Month Due',
        paidAmount: 0,
        remarks: 'Due this month',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1006',
        description: 'Laptop Installment – Jun 2025',
        dueDate: '2025-06-10',
        totalInstallment: 25000,
        installmentDue: 0,
        status: 'Paid',
        paidAmount: 25000,
        remarks: 'Paid via debit card',
        branch: 'Lahore Branch',
      },
      {
        instId: 'INV-1007',
        description: 'Mobile Installment – Jul 2025',
        dueDate: '2025-07-10',
        totalInstallment: 10000,
        installmentDue: 0,
        status: 'Paid',
        paidAmount: 10000,
        remarks: 'On-time payment',
        branch: 'Lahore Branch',
      },
      {
        instId: 'INV-1008',
        description: 'Mobile Installment – Aug 2025',
        dueDate: '2025-08-10',
        totalInstallment: 10000,
        installmentDue: 10000,
        status: 'Current Month Due',
        paidAmount: 0,
        remarks: 'Upcoming payment',
        branch: 'Lahore Branch',
      },
      {
        instId: 'INV-1009',
        description: 'Refrigerator Installment – Sep 2025',
        dueDate: '2025-09-10',
        totalInstallment: 30000,
        installmentDue: 15000,
        status: 'Partial',
        paidAmount: 15000,
        remarks: 'Remaining half pending',
        branch: 'Islamabad Branch',
      },
      {
        instId: 'INV-1010',
        description: 'Refrigerator Installment – Oct 2025',
        dueDate: '2025-10-10',
        totalInstallment: 30000,
        installmentDue: 30000,
        status: 'Overdue',
        paidAmount: 0,
        remarks: 'Reminder sent',
        branch: 'Islamabad Branch',
      },
      {
        instId: 'INV-1011',
        description: 'AC Installment – Nov 2025',
        dueDate: '2025-11-10',
        totalInstallment: 40000,
        installmentDue: 40000,
        status: 'Current Month Due',
        paidAmount: 0,
        remarks: 'Payment expected this week',
        branch: 'Karachi Main Branch',
      },
      {
        instId: 'INV-1012',
        description: 'AC Installment – Dec 2025',
        dueDate: '2025-12-10',
        totalInstallment: 40000,
        installmentDue: 40000,
        status: 'Upcoming',
        paidAmount: 0,
        remarks: 'Future invoice',
        branch: 'Karachi Main Branch',
      },
    ],
    summary: {
      totalBalance: 315000,
      totalOutstandingBalance: 195000,
      currentMonthTotal: 80000,
      currentMonthDue: 80000,
      currentMonthPaid: 0,
    },
  }
